Feature/apis
ashishkava/NODEAPI pull request #10
Opened 2021-12-22 05:22 UTC by ashishkava

2021-12-22 08:00 UTC, jaimin45 requested changes

2021-12-22 08:00 UTC, jaimin45 commented on app.js
> +module.exports = app;
Add line

2021-12-22 08:00 UTC, jaimin45 commented on index.jade
> +  h3= Title
add line

2021-12-22 08:01 UTC, JainishaParmar requested changes

2021-12-22 09:17 UTC, jaimin45 requested changes

2021-12-22 09:17 UTC, jaimin45 commented on app.js
> +module.exports = app;
add line

2021-12-22 09:17 UTC, jaimin45 commented on index.jade
> +  p Quick Start
add line

2021-12-22 09:17 UTC, jaimin45 commented on name.js
> +module.export = app;
add line

2021-12-22 09:17 UTC, jaimin45 commented on tutorial.js
> +module.export = router;
add line

2021-12-22 09:17 UTC, jaimin45 commented on tutorial.schema.js
> +  module.exports = mongoose.model("Tutorial1", tutorialSchema.js);
add line

2021-12-22 09:22 UTC, JainishaParmar requested changes

2021-12-22 09:22 UTC, JainishaParmar commented on app.js
> +module.exports = app;
enter new line

2021-12-22 09:22 UTC, JainishaParmar commented on tutorial.js
> +router.delete("/:tutorialId", deleteTutorials);
tutorial id should `id`

2021-12-22 09:22 UTC, JainishaParmar commented on users.js
> +  dsfsdf
remove this `dsfsdf`

2021-12-22 09:22 UTC, JainishaParmar commented on www.js
> +  // }
remove this

2021-12-22 10:09 UTC, jaimin45 approved these changes

2021-12-22 10:29 UTC, jaimin45 requested changes

2021-12-22 10:29 UTC, jaimin45 commented on Eslintrc.json
> +      "prettier/prettier": "error",
remove prettier

2021-12-22 10:31 UTC, JainishaParmar requested changes

2021-12-22 10:31 UTC, JainishaParmar commented on swagger.yaml
> +          description: "Invalid input"
add 500 response in all APIs and add schema ```$ref: "#/definitions/500Response"```

2021-12-22 10:31 UTC, JainishaParmar commented on swagger.yaml
> +          description: "Not found"
add schema ```$ref: "#/definitions/404Response"```

2021-12-22 10:31 UTC, JainishaParmar commented on tutorial.js
> +router.delete("/:tutorialid", deleteTutorials);
change ```tutorialid``` to ```id```

2021-12-22 10:31 UTC, JainishaParmar commented on tutorial.schema.js
> +    },
please remove id createdAt and updatedAt it should autogenerated and add title and description

2021-12-22 12:35 UTC, kapilbarad requested changes

2021-12-22 12:35 UTC, kapilbarad commented on app.js
> +const TutorialRouter = require('./routes/tutorial.routes');
Bane should be `tutorialRouter`

2021-12-22 12:35 UTC, kapilbarad commented on name.js
> +const express = require("express");
Please remove this file as It's not being used anywhere.

2021-12-22 12:35 UTC, kapilbarad commented on swagger.yaml
> +    parameters:
No need of this parameters here as we don't have id in path parameters for Create and Get routes.

2021-12-23 05:14 UTC, jaimin45 approved these changes

2021-12-23 05:17 UTC, JainishaParmar approved these changes

2021-12-23 05:20 UTC, JainishaParmar approved these changes

2021-12-23 13:39 UTC, kapilbarad approved these changes

2021-12-27 04:54 UTC, JainishaParmar approved these changes

2021-12-27 09:22 UTC, merged