Validation update
ashishkava/NODEAPI pull request #11
Opened 2021-12-27 13:35 UTC by ashishkava

2021-12-28 04:17 UTC, jaimin45 requested changes

2021-12-28 04:17 UTC, jaimin45 commented on JoiValidation/joiValidation.js
> +  schema,
Add line end of the code

2021-12-28 04:17 UTC, jaimin45 commented on controller/Controller.js
> +  deleteTutorial,
Add line end of the code

2021-12-28 04:17 UTC, jaimin45 commented on swagger.yaml
> +        type: string
Add line end of the code

2021-12-28 04:17 UTC, jaimin45 commented on views/index.jade
> +
Add line end of the code

2021-12-28 06:21 UTC, jaimin45 approved these changes

2021-12-28 06:55 UTC, kapilbarad requested changes

2021-12-28 06:55 UTC, kapilbarad commented on controller/Controller.js
> +      res.status(400).send({ message: 'Invalid Tutorial id' });
Responses should be match with swagger definition.

2021-12-28 06:56 UTC, kapilbarad commented
@ashishkava Did you folowed correct steps before starting a new feature?

2021-12-28 09:57 UTC, kapilbarad requested changes

2021-12-28 09:57 UTC, kapilbarad commented on gitignore
> +node_modules
node_modules is duplicate.

2021-12-28 09:57 UTC, kapilbarad commented on routes/tutorial.routes.js
> +router.patch("/:Id", updateTutorial);
Should be `id` instead of `Id`.

2021-12-29 04:41 UTC, kapilbarad requested changes

2021-12-29 04:41 UTC, kapilbarad commented on Controller.js
> +/* eslint-disable no-undef */
We should not disable any eslint rules.

2021-12-29 04:41 UTC, kapilbarad commented on Controller.js
> +    res.status(500).send({ message: "Internal Error" });
No need to change the error message. It's correct.

2021-12-29 11:34 UTC, JainishaParmar approved these changes

2021-12-30 05:06 UTC, kapilbarad requested changes

2021-12-30 05:06 UTC, kapilbarad commented on Controller.js
> +/* eslint-disable no-undef */
Please remove this file.

2021-12-30 05:06 UTC, kapilbarad commented on controller/Controller.js
> +  const tutorial = new Tutorial({
Shift this after line no 26 (after validate) and use value from validate as tutorial data:
```
const { error, value } = postTutorialSchema.validate(req.body);

if (error) return res.status(400).send({ message: error.message });
const tutorial = new Tutorial(value)
await tutorial.save();
res.status(201).send();
```

2021-12-30 05:06 UTC, kapilbarad commented on controller/Controller.js
> +  const tutorial = new Tutorial({
Also do the same in updateTutorial

2021-12-30 06:27 UTC, JainishaParmar approved these changes

2021-12-30 07:44 UTC, kapilbarad requested changes

2021-12-30 07:44 UTC, kapilbarad commented on controller/Controller.js
>    const tutorial = new Tutorial({
We don't need this line now.
We've already created new tutorial in 25 line. Also Please test your APIs again.

2021-12-30 07:44 UTC, kapilbarad commented on controller/Controller.js
> +    const tutorial = new Tutorial(value)
Why are we creating new tutorial here? This is only valid for New Tutorial API. Here we only need to update the tutorial which is already happening in like 44.

2021-12-30 09:05 UTC, kapilbarad requested changes

2021-12-30 09:05 UTC, kapilbarad commented on controller/Controller.js
> +      res.status(400).send({ message: "Invalid Tutorial details" });
This will never occur for Create Tutorial API, We only need:
```
} catch (error) {
   res.status(500).send({ message: "Internal Server Error" });
}
```

2021-12-30 09:05 UTC, kapilbarad commented on controller/Controller.js
> +      res.status(404).send({ message: 'Invalid Tutorial Id' });
Error message should be `Tutorial not found`

2021-12-30 09:05 UTC, kapilbarad commented on controller/Controller.js
> +      res.status(404).send({ message: "Invalid Tutorial Id" });
Message should be `Tutorial not found`

2021-12-30 10:14 UTC, kapilbarad approved these changes

2021-12-30 10:18 UTC, merged