docs:feature/authentication
ashishkava/NODEAPI pull request #14
Opened 2022-01-04 05:17 UTC by ashishkava

2022-01-04 11:14 UTC, kapilbarad requested changes

2022-01-04 12:36 UTC, JainishaParmar approved these changes

2022-01-04 12:38 UTC, jaimin45 approved these changes

2022-01-05 09:35 UTC, kapilbarad requested changes

2022-01-05 09:35 UTC, kapilbarad commented on controller/Controller.js
> +    res.status(201).send(tutorials);
Did you teat after modifying this? This will throw error as there is no variable named `tutorial`

2022-01-05 09:35 UTC, kapilbarad commented on swagger.yaml
> +    name: access_token
THe in: should be header, I was talking about name property.

2022-01-05 09:59 UTC, jaimin45 requested changes

2022-01-05 09:59 UTC, jaimin45 commented on swagger.yaml
>          '400':
Add 409 response

2022-01-05 09:59 UTC, jaimin45 commented on swagger.yaml
> +        description: Tutorial id
remove tutorials

2022-01-05 09:59 UTC, jaimin45 commented on swagger.yaml
> +      - name: 'email'
remove email as query used body request

2022-01-05 09:59 UTC, jaimin45 commented on swagger.yaml
> +        '201':
not 201 used 200

2022-01-05 09:59 UTC, jaimin45 commented on swagger.yaml
> +        '404':
remove 404 ans used 401

2022-01-05 09:59 UTC, jaimin45 commented on swagger.yaml
>          '204':
remove 204 AND USED 201

2022-01-05 09:59 UTC, jaimin45 commented on swagger.yaml
>              $ref: '#/definitions/404Response'
USED valid response

2022-01-05 09:59 UTC, jaimin45 commented on swagger.yaml
>          '404':
used 201 400 and 500 response

2022-01-05 09:59 UTC, jaimin45 commented on swagger.yaml
>  securityDefinitions:
remove security

2022-01-05 10:03 UTC, JainishaParmar requested changes

2022-01-05 10:03 UTC, JainishaParmar commented on swagger.yaml
> +        '404':
Add 201 response

2022-01-05 10:03 UTC, JainishaParmar commented on swagger.yaml
> +    in: "Authorization"
Remove this

2022-01-05 10:03 UTC, JainishaParmar commented on swagger.yaml
> +      - lastname
It should ```firstName``` and ```lastName```

2022-01-05 10:15 UTC, kapilbarad approved these changes

2022-01-05 10:16 UTC, merged